// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: yelo.proto

package yelo

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type SortOrder int32

const (
	SortOrder_ASC  SortOrder = 0
	SortOrder_DESC SortOrder = 1
)

// Enum value maps for SortOrder.
var (
	SortOrder_name = map[int32]string{
		0: "ASC",
		1: "DESC",
	}
	SortOrder_value = map[string]int32{
		"ASC":  0,
		"DESC": 1,
	}
)

func (x SortOrder) Enum() *SortOrder {
	p := new(SortOrder)
	*p = x
	return p
}

func (x SortOrder) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortOrder) Descriptor() protoreflect.EnumDescriptor {
	return file_yelo_proto_enumTypes[0].Descriptor()
}

func (SortOrder) Type() protoreflect.EnumType {
	return &file_yelo_proto_enumTypes[0]
}

func (x SortOrder) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SortOrder.Descriptor instead.
func (SortOrder) EnumDescriptor() ([]byte, []int) {
	return file_yelo_proto_rawDescGZIP(), []int{0}
}

type ListPlacesRequest_ListPlacesSortField int32

const (
	ListPlacesRequest_PLACE_NAME ListPlacesRequest_ListPlacesSortField = 0
	ListPlacesRequest_DISTANCE   ListPlacesRequest_ListPlacesSortField = 1
)

// Enum value maps for ListPlacesRequest_ListPlacesSortField.
var (
	ListPlacesRequest_ListPlacesSortField_name = map[int32]string{
		0: "PLACE_NAME",
		1: "DISTANCE",
	}
	ListPlacesRequest_ListPlacesSortField_value = map[string]int32{
		"PLACE_NAME": 0,
		"DISTANCE":   1,
	}
)

func (x ListPlacesRequest_ListPlacesSortField) Enum() *ListPlacesRequest_ListPlacesSortField {
	p := new(ListPlacesRequest_ListPlacesSortField)
	*p = x
	return p
}

func (x ListPlacesRequest_ListPlacesSortField) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ListPlacesRequest_ListPlacesSortField) Descriptor() protoreflect.EnumDescriptor {
	return file_yelo_proto_enumTypes[1].Descriptor()
}

func (ListPlacesRequest_ListPlacesSortField) Type() protoreflect.EnumType {
	return &file_yelo_proto_enumTypes[1]
}

func (x ListPlacesRequest_ListPlacesSortField) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ListPlacesRequest_ListPlacesSortField.Descriptor instead.
func (ListPlacesRequest_ListPlacesSortField) EnumDescriptor() ([]byte, []int) {
	return file_yelo_proto_rawDescGZIP(), []int{3, 0}
}

type AddNewPlaceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string       `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PlaceType   int32        `protobuf:"varint,2,opt,name=place_type,json=placeType,proto3" json:"place_type,omitempty"`
	Coordinates *Coordinates `protobuf:"bytes,3,opt,name=coordinates,proto3" json:"coordinates,omitempty"`
	Description string       `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *AddNewPlaceRequest) Reset() {
	*x = AddNewPlaceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yelo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddNewPlaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddNewPlaceRequest) ProtoMessage() {}

func (x *AddNewPlaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yelo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddNewPlaceRequest.ProtoReflect.Descriptor instead.
func (*AddNewPlaceRequest) Descriptor() ([]byte, []int) {
	return file_yelo_proto_rawDescGZIP(), []int{0}
}

func (x *AddNewPlaceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddNewPlaceRequest) GetPlaceType() int32 {
	if x != nil {
		return x.PlaceType
	}
	return 0
}

func (x *AddNewPlaceRequest) GetCoordinates() *Coordinates {
	if x != nil {
		return x.Coordinates
	}
	return nil
}

func (x *AddNewPlaceRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type Coordinates struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Latitude  float32 `protobuf:"fixed32,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude float32 `protobuf:"fixed32,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
}

func (x *Coordinates) Reset() {
	*x = Coordinates{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yelo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Coordinates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coordinates) ProtoMessage() {}

func (x *Coordinates) ProtoReflect() protoreflect.Message {
	mi := &file_yelo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coordinates.ProtoReflect.Descriptor instead.
func (*Coordinates) Descriptor() ([]byte, []int) {
	return file_yelo_proto_rawDescGZIP(), []int{1}
}

func (x *Coordinates) GetLatitude() float32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Coordinates) GetLongitude() float32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type AddNewPlaceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlaceId int64 `protobuf:"varint,1,opt,name=place_id,json=placeId,proto3" json:"place_id,omitempty"`
}

func (x *AddNewPlaceResponse) Reset() {
	*x = AddNewPlaceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yelo_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddNewPlaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddNewPlaceResponse) ProtoMessage() {}

func (x *AddNewPlaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_yelo_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddNewPlaceResponse.ProtoReflect.Descriptor instead.
func (*AddNewPlaceResponse) Descriptor() ([]byte, []int) {
	return file_yelo_proto_rawDescGZIP(), []int{2}
}

func (x *AddNewPlaceResponse) GetPlaceId() int64 {
	if x != nil {
		return x.PlaceId
	}
	return 0
}

type ListPlacesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SearchText string                                `protobuf:"bytes,1,opt,name=search_text,json=searchText,proto3" json:"search_text,omitempty"`
	PlaceType  []int32                               `protobuf:"varint,2,rep,packed,name=place_type,json=placeType,proto3" json:"place_type,omitempty"`
	SortOrder  SortOrder                             `protobuf:"varint,3,opt,name=sort_order,json=sortOrder,proto3,enum=yelo.SortOrder" json:"sort_order,omitempty"`
	SortField  ListPlacesRequest_ListPlacesSortField `protobuf:"varint,4,opt,name=sort_field,json=sortField,proto3,enum=yelo.ListPlacesRequest_ListPlacesSortField" json:"sort_field,omitempty"`
}

func (x *ListPlacesRequest) Reset() {
	*x = ListPlacesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yelo_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPlacesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPlacesRequest) ProtoMessage() {}

func (x *ListPlacesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yelo_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPlacesRequest.ProtoReflect.Descriptor instead.
func (*ListPlacesRequest) Descriptor() ([]byte, []int) {
	return file_yelo_proto_rawDescGZIP(), []int{3}
}

func (x *ListPlacesRequest) GetSearchText() string {
	if x != nil {
		return x.SearchText
	}
	return ""
}

func (x *ListPlacesRequest) GetPlaceType() []int32 {
	if x != nil {
		return x.PlaceType
	}
	return nil
}

func (x *ListPlacesRequest) GetSortOrder() SortOrder {
	if x != nil {
		return x.SortOrder
	}
	return SortOrder_ASC
}

func (x *ListPlacesRequest) GetSortField() ListPlacesRequest_ListPlacesSortField {
	if x != nil {
		return x.SortField
	}
	return ListPlacesRequest_PLACE_NAME
}

type ListPlacesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Places []*Place            `protobuf:"bytes,1,rep,name=places,proto3" json:"places,omitempty"`
	Page   *PaginationResponse `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
}

func (x *ListPlacesResponse) Reset() {
	*x = ListPlacesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yelo_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPlacesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPlacesResponse) ProtoMessage() {}

func (x *ListPlacesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_yelo_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPlacesResponse.ProtoReflect.Descriptor instead.
func (*ListPlacesResponse) Descriptor() ([]byte, []int) {
	return file_yelo_proto_rawDescGZIP(), []int{4}
}

func (x *ListPlacesResponse) GetPlaces() []*Place {
	if x != nil {
		return x.Places
	}
	return nil
}

func (x *ListPlacesResponse) GetPage() *PaginationResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

type Place struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int64        `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PlaceType   int32        `protobuf:"varint,3,opt,name=place_type,json=placeType,proto3" json:"place_type,omitempty"`
	Coordinates *Coordinates `protobuf:"bytes,4,opt,name=coordinates,proto3" json:"coordinates,omitempty"`
	Description string       `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *Place) Reset() {
	*x = Place{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yelo_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Place) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Place) ProtoMessage() {}

func (x *Place) ProtoReflect() protoreflect.Message {
	mi := &file_yelo_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Place.ProtoReflect.Descriptor instead.
func (*Place) Descriptor() ([]byte, []int) {
	return file_yelo_proto_rawDescGZIP(), []int{5}
}

func (x *Place) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Place) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Place) GetPlaceType() int32 {
	if x != nil {
		return x.PlaceType
	}
	return 0
}

func (x *Place) GetCoordinates() *Coordinates {
	if x != nil {
		return x.Coordinates
	}
	return nil
}

func (x *Place) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type PaginationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From int32 `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	Size int32 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *PaginationRequest) Reset() {
	*x = PaginationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yelo_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaginationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationRequest) ProtoMessage() {}

func (x *PaginationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yelo_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationRequest.ProtoReflect.Descriptor instead.
func (*PaginationRequest) Descriptor() ([]byte, []int) {
	return file_yelo_proto_rawDescGZIP(), []int{6}
}

func (x *PaginationRequest) GetFrom() int32 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *PaginationRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type PaginationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalCount int32 `protobuf:"varint,1,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Cursor     int32 `protobuf:"varint,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	HasMore    bool  `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
}

func (x *PaginationResponse) Reset() {
	*x = PaginationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yelo_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaginationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationResponse) ProtoMessage() {}

func (x *PaginationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_yelo_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationResponse.ProtoReflect.Descriptor instead.
func (*PaginationResponse) Descriptor() ([]byte, []int) {
	return file_yelo_proto_rawDescGZIP(), []int{7}
}

func (x *PaginationResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *PaginationResponse) GetCursor() int32 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *PaginationResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

var File_yelo_proto protoreflect.FileDescriptor

var file_yelo_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x79, 0x65, 0x6c, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x79, 0x65,
	0x6c, 0x6f, 0x22, 0x9e, 0x01, 0x0a, 0x12, 0x41, 0x64, 0x64, 0x4e, 0x65, 0x77, 0x50, 0x6c, 0x61,
	0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a,
	0x0a, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x09, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x33, 0x0a, 0x0b,
	0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x79, 0x65, 0x6c, 0x6f, 0x2e, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e,
	0x61, 0x74, 0x65, 0x73, 0x52, 0x0b, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65,
	0x73, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x22, 0x47, 0x0a, 0x0b, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74,
	0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x22, 0x34, 0x0a, 0x13,
	0x41, 0x64, 0x64, 0x4e, 0x65, 0x77, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x42, 0x02, 0x30, 0x01, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x63, 0x65,
	0x49, 0x64, 0x22, 0x84, 0x02, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x6c, 0x61, 0x63, 0x65,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x5f, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x54, 0x65, 0x78, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x6c, 0x61,
	0x63, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x05, 0x52, 0x09, 0x70,
	0x6c, 0x61, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x2e, 0x0a, 0x0a, 0x73, 0x6f, 0x72, 0x74,
	0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x79,
	0x65, 0x6c, 0x6f, 0x2e, 0x53, 0x6f, 0x72, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x09, 0x73,
	0x6f, 0x72, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x4a, 0x0a, 0x0a, 0x73, 0x6f, 0x72, 0x74,
	0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2b, 0x2e, 0x79,
	0x65, 0x6c, 0x6f, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x73,
	0x53, 0x6f, 0x72, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x09, 0x73, 0x6f, 0x72, 0x74, 0x46,
	0x69, 0x65, 0x6c, 0x64, 0x22, 0x33, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x6c, 0x61, 0x63,
	0x65, 0x73, 0x53, 0x6f, 0x72, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x0e, 0x0a, 0x0a, 0x50,
	0x4c, 0x41, 0x43, 0x45, 0x5f, 0x4e, 0x41, 0x4d, 0x45, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x44,
	0x49, 0x53, 0x54, 0x41, 0x4e, 0x43, 0x45, 0x10, 0x01, 0x22, 0x67, 0x0a, 0x12, 0x4c, 0x69, 0x73,
	0x74, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x23, 0x0a, 0x06, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0b, 0x2e, 0x79, 0x65, 0x6c, 0x6f, 0x2e, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x52, 0x06, 0x70, 0x6c,
	0x61, 0x63, 0x65, 0x73, 0x12, 0x2c, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x18, 0x2e, 0x79, 0x65, 0x6c, 0x6f, 0x2e, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x04, 0x70, 0x61,
	0x67, 0x65, 0x22, 0xa5, 0x01, 0x0a, 0x05, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x42, 0x02, 0x30, 0x01, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x33, 0x0a, 0x0b, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74,
	0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x79, 0x65, 0x6c, 0x6f, 0x2e,
	0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x52, 0x0b, 0x63, 0x6f, 0x6f,
	0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x3b, 0x0a, 0x11, 0x50, 0x61,
	0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x66,
	0x72, 0x6f, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x22, 0x68, 0x0a, 0x12, 0x50, 0x61, 0x67, 0x69, 0x6e,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a,
	0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x63, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x63, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x12, 0x19, 0x0a, 0x08, 0x68, 0x61, 0x73, 0x5f, 0x6d, 0x6f,
	0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x68, 0x61, 0x73, 0x4d, 0x6f, 0x72,
	0x65, 0x2a, 0x1e, 0x0a, 0x09, 0x53, 0x6f, 0x72, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x07,
	0x0a, 0x03, 0x41, 0x53, 0x43, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x44, 0x45, 0x53, 0x43, 0x10,
	0x01, 0x32, 0x92, 0x01, 0x0a, 0x0b, 0x59, 0x65, 0x6c, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x42, 0x0a, 0x0b, 0x41, 0x64, 0x64, 0x4e, 0x65, 0x77, 0x50, 0x6c, 0x61, 0x63, 0x65,
	0x12, 0x18, 0x2e, 0x79, 0x65, 0x6c, 0x6f, 0x2e, 0x41, 0x64, 0x64, 0x4e, 0x65, 0x77, 0x50, 0x6c,
	0x61, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x79, 0x65, 0x6c,
	0x6f, 0x2e, 0x41, 0x64, 0x64, 0x4e, 0x65, 0x77, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3f, 0x0a, 0x0a, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x6c, 0x61,
	0x63, 0x65, 0x73, 0x12, 0x17, 0x2e, 0x79, 0x65, 0x6c, 0x6f, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x50,
	0x6c, 0x61, 0x63, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x79,
	0x65, 0x6c, 0x6f, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x28, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x61, 0x75, 0x72, 0x73, 0x61, 0x67, 0x61, 0x72, 0x4d, 0x54,
	0x2f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x65, 0x72, 0x2f, 0x70, 0x62, 0x2f, 0x79, 0x65, 0x6c, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_yelo_proto_rawDescOnce sync.Once
	file_yelo_proto_rawDescData = file_yelo_proto_rawDesc
)

func file_yelo_proto_rawDescGZIP() []byte {
	file_yelo_proto_rawDescOnce.Do(func() {
		file_yelo_proto_rawDescData = protoimpl.X.CompressGZIP(file_yelo_proto_rawDescData)
	})
	return file_yelo_proto_rawDescData
}

var file_yelo_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_yelo_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_yelo_proto_goTypes = []interface{}{
	(SortOrder)(0), // 0: yelo.SortOrder
	(ListPlacesRequest_ListPlacesSortField)(0), // 1: yelo.ListPlacesRequest.ListPlacesSortField
	(*AddNewPlaceRequest)(nil),                 // 2: yelo.AddNewPlaceRequest
	(*Coordinates)(nil),                        // 3: yelo.Coordinates
	(*AddNewPlaceResponse)(nil),                // 4: yelo.AddNewPlaceResponse
	(*ListPlacesRequest)(nil),                  // 5: yelo.ListPlacesRequest
	(*ListPlacesResponse)(nil),                 // 6: yelo.ListPlacesResponse
	(*Place)(nil),                              // 7: yelo.Place
	(*PaginationRequest)(nil),                  // 8: yelo.PaginationRequest
	(*PaginationResponse)(nil),                 // 9: yelo.PaginationResponse
}
var file_yelo_proto_depIdxs = []int32{
	3, // 0: yelo.AddNewPlaceRequest.coordinates:type_name -> yelo.Coordinates
	0, // 1: yelo.ListPlacesRequest.sort_order:type_name -> yelo.SortOrder
	1, // 2: yelo.ListPlacesRequest.sort_field:type_name -> yelo.ListPlacesRequest.ListPlacesSortField
	7, // 3: yelo.ListPlacesResponse.places:type_name -> yelo.Place
	9, // 4: yelo.ListPlacesResponse.page:type_name -> yelo.PaginationResponse
	3, // 5: yelo.Place.coordinates:type_name -> yelo.Coordinates
	2, // 6: yelo.YeloService.AddNewPlace:input_type -> yelo.AddNewPlaceRequest
	5, // 7: yelo.YeloService.ListPlaces:input_type -> yelo.ListPlacesRequest
	4, // 8: yelo.YeloService.AddNewPlace:output_type -> yelo.AddNewPlaceResponse
	6, // 9: yelo.YeloService.ListPlaces:output_type -> yelo.ListPlacesResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_yelo_proto_init() }
func file_yelo_proto_init() {
	if File_yelo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_yelo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddNewPlaceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yelo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Coordinates); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yelo_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddNewPlaceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yelo_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPlacesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yelo_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPlacesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yelo_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Place); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yelo_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaginationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yelo_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaginationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_yelo_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_yelo_proto_goTypes,
		DependencyIndexes: file_yelo_proto_depIdxs,
		EnumInfos:         file_yelo_proto_enumTypes,
		MessageInfos:      file_yelo_proto_msgTypes,
	}.Build()
	File_yelo_proto = out.File
	file_yelo_proto_rawDesc = nil
	file_yelo_proto_goTypes = nil
	file_yelo_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// YeloServiceClient is the client API for YeloService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type YeloServiceClient interface {
	AddNewPlace(ctx context.Context, in *AddNewPlaceRequest, opts ...grpc.CallOption) (*AddNewPlaceResponse, error)
	ListPlaces(ctx context.Context, in *ListPlacesRequest, opts ...grpc.CallOption) (*ListPlacesResponse, error)
}

type yeloServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewYeloServiceClient(cc grpc.ClientConnInterface) YeloServiceClient {
	return &yeloServiceClient{cc}
}

func (c *yeloServiceClient) AddNewPlace(ctx context.Context, in *AddNewPlaceRequest, opts ...grpc.CallOption) (*AddNewPlaceResponse, error) {
	out := new(AddNewPlaceResponse)
	err := c.cc.Invoke(ctx, "/yelo.YeloService/AddNewPlace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *yeloServiceClient) ListPlaces(ctx context.Context, in *ListPlacesRequest, opts ...grpc.CallOption) (*ListPlacesResponse, error) {
	out := new(ListPlacesResponse)
	err := c.cc.Invoke(ctx, "/yelo.YeloService/ListPlaces", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// YeloServiceServer is the server API for YeloService service.
type YeloServiceServer interface {
	AddNewPlace(context.Context, *AddNewPlaceRequest) (*AddNewPlaceResponse, error)
	ListPlaces(context.Context, *ListPlacesRequest) (*ListPlacesResponse, error)
}

// UnimplementedYeloServiceServer can be embedded to have forward compatible implementations.
type UnimplementedYeloServiceServer struct {
}

func (*UnimplementedYeloServiceServer) AddNewPlace(context.Context, *AddNewPlaceRequest) (*AddNewPlaceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddNewPlace not implemented")
}
func (*UnimplementedYeloServiceServer) ListPlaces(context.Context, *ListPlacesRequest) (*ListPlacesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPlaces not implemented")
}

func RegisterYeloServiceServer(s *grpc.Server, srv YeloServiceServer) {
	s.RegisterService(&_YeloService_serviceDesc, srv)
}

func _YeloService_AddNewPlace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddNewPlaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(YeloServiceServer).AddNewPlace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/yelo.YeloService/AddNewPlace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(YeloServiceServer).AddNewPlace(ctx, req.(*AddNewPlaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _YeloService_ListPlaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPlacesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(YeloServiceServer).ListPlaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/yelo.YeloService/ListPlaces",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(YeloServiceServer).ListPlaces(ctx, req.(*ListPlacesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _YeloService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "yelo.YeloService",
	HandlerType: (*YeloServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddNewPlace",
			Handler:    _YeloService_AddNewPlace_Handler,
		},
		{
			MethodName: "ListPlaces",
			Handler:    _YeloService_ListPlaces_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "yelo.proto",
}
